"""migracion_inicial

Revision ID: 98f883ddcb8e
Revises: 
Create Date: 2026-05-26 14:57:20.791453

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel 
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f883ddcb8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    op.create_table('clasificaciones_equipo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clasificaciones_equipo_nombre'), 'clasificaciones_equipo', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rol', sa.Enum('COORDINADOR', 'SUPERVISOR', 'USUARIO', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('equipos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_equipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clasificacion_id', sa.Uuid(), nullable=True),
    sa.Column('equipo_padre_id', sa.Uuid(), nullable=True),
    sa.Column('area_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('potencia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('voltaje', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('rpm', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('capacidad', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('anio_fabricacion', sa.Integer(), nullable=True),
    sa.Column('proveedor', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('fecha_adquisicion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('OPERATIVO', 'PARADO', 'REPARACION', 'BAJA', name='estadoequipoenum'), nullable=False),
    sa.Column('motivo_estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['clasificacion_id'], ['clasificaciones_equipo.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_padre_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_codigo_equipo'), 'equipos', ['codigo_equipo'], unique=True)
    op.create_index(op.f('ix_equipos_estado'), 'equipos', ['estado'], unique=False)
    op.create_index(op.f('ix_equipos_nombre'), 'equipos', ['nombre'], unique=False)
    op.create_table('equipos_repuestos_necesarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipo_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_repuesto', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('para_que', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cantidad_necesaria', sa.Float(), nullable=False),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_repuestos_necesarios_equipo_id'), 'equipos_repuestos_necesarios', ['equipo_id'], unique=False)
    op.create_table('fotos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipo_id', sa.Uuid(), nullable=False),
    sa.Column('cloudinary_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tipo_foto', sa.Enum('PLACA', 'GENERAL', 'FALLA', 'DETALLE', name='tipofotoenum'), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_equipo_id'), 'fotos', ['equipo_id'], unique=False)
    op.create_table('historial_cambios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('campo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('valor_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_nuevo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_cambios_equipo_id'), 'historial_cambios', ['equipo_id'], unique=False)
    op.create_table('mantenimientos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.Enum('PREVENTIVO', 'CORRECTIVO', 'EMERGENCIA', name='tipomantenimientoenum'), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trabajo_realizado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('REALIZADO', 'PENDIENTE', name='estadomantenimientoenum'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_equipo_id'), 'mantenimientos', ['equipo_id'], unique=False)
    op.create_table('mantenimientos_repuestos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mantenimiento_id', sa.Uuid(), nullable=False),
    sa.Column('repuesto_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_usada', sa.Float(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_repuestos_mantenimiento_id'), 'mantenimientos_repuestos', ['mantenimiento_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_repuestos_repuesto_id'), 'mantenimientos_repuestos', ['repuesto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mantenimientos_repuestos_repuesto_id'), table_name='mantenimientos_repuestos')
    op.drop_index(op.f('ix_mantenimientos_repuestos_mantenimiento_id'), table_name='mantenimientos_repuestos')
    op.drop_table('mantenimientos_repuestos')
    op.drop_index(op.f('ix_mantenimientos_equipo_id'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    op.drop_index(op.f('ix_historial_cambios_equipo_id'), table_name='historial_cambios')
    op.drop_table('historial_cambios')
    op.drop_index(op.f('ix_fotos_equipo_id'), table_name='fotos')
    op.drop_table('fotos')
    op.drop_index(op.f('ix_equipos_repuestos_necesarios_equipo_id'), table_name='equipos_repuestos_necesarios')
    op.drop_table('equipos_repuestos_necesarios')
    op.drop_index(op.f('ix_equipos_nombre'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_estado'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_codigo_equipo'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clasificaciones_equipo_nombre'), table_name='clasificaciones_equipo')
    op.drop_table('clasificaciones_equipo')
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
