"""add realizado_por to mantenimiento

Revision ID: e439c6b3b436
Revises: 49d8b08bd258
Create Date: 2026-05-27 11:52:51.451197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e439c6b3b436'
down_revision: Union[str, None] = '49d8b08bd258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mantenimientos', sa.Column('realizado_por', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mantenimientos', 'realizado_por')
    # ### end Alembic commands ###
